### PR TITLE
Fix for Qt6 compatibility

### PR DESCRIPTION
**Pull request by abdnh**
The Qt5 compatibility layer is disabled by default in Anki 23.10

### CODE REVIEW

**Comment by AnKingMed** [comment]
@Ambriel?   If you're not interested in maintaining this add-on anymore, I'd be happy to take over as well. If you are wanting to keep it, can you merge this and upload to Ankiweb?

**Comment by DoctorToBeIn23** [comment]
Just following up on this, any chance we can get the update pushed or take over?

**Comment by Ambriel** [comment]
> @Ambriel are you able to update this?

Sorry, I have been MIA for a while and didn't expect to receive replies to that. I can push this update. If it comes to the point I want to detach from the project in the future, I wouldn't mind transferring it. I also wouldn't mind adding you onto this project where you're able to make the updates independently without my approval. My understanding is the Anki Web does not support his yet, and I'd have to do it? Anyway, just let me know how I can help. I will be glad to assist, and thank you very much for your patch.

**Comment by Ambriel** [comment]
> The Qt5 compatibility layer is disabled by default in Anki 23.10

Thank you, I'll add the patch. Please let me know if you need anything else. I can add anyone to the project that'd like to be added.

**Comment by AnKingMed** [comment]
AnkiWeb doesn't support sharing. You either have to share an account or transfer it. If you're not interested in maintaining it or want to transfer that part and just give me access here, we just have to ask Damien and he'll do it. I've done that with a few other add-ons. I don't mean to take credit or anything for them, just trying to do my part to help out :)

**Review by Ambriel — APPROVED** [review]
Fix for Qt6 compatibility added by adbnh

**Comment by Ambriel** [comment]
> AnkiWeb doesn't support sharing. You either have to share an account or transfer it. If you're not interested in maintaining it or want to transfer that part and just give me access here, we just have to ask Damien and he'll do it. I've done that with a few other add-ons. I don't mean to take credit or anything for them, just trying to do my part to help out :)

It's no problem AnKingMed. We'll take care of this now. Just give me a second to reread your options.

**Comment by Ambriel** [comment]
> AnkiWeb doesn't support sharing. You either have to share an account or transfer it. If you're not interested in maintaining it or want to transfer that part and just give me access here, we just have to ask Damien and he'll do it. I've done that with a few other add-ons. I don't mean to take credit or anything for them, just trying to do my part to help out :)

I'm working on giving you access here on github. I'll also share my AnkiWeb account.

**Comment by AnKingMed** [comment]
Feel free to email me at ankingmed@gmail.com as well if needed

**Comment by Ambriel** [comment]
> [abdnh](/abdnh)

I am writing you from there right now.

**Comment by Ambriel** [comment]
> AnKingMed

Please check your email, and also except my GitHub invite. I've added you as a contributor to this project.

**Pull request merged**
